/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package path;

import path.mainWindow;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import path.mainWindow;

/**
 *
 * @author Usuario
 */
public class AyudaViajero extends javax.swing.JFrame {
    
    /**
     * Creates new form AyudaViajero
     */
    public AyudaViajero() {
        initComponents();
        List cities = new LinkedList<>();
        
        cities.add("Curridabat");
        cities.add("Barbacoas");
        cities.add("Hatillo");
        cities.add("Santa Ana");
        cities.add("Santiago");
        cities.add("San Antonio");
        cities.add("Sabanilla");
        cities.add("Desamparados");
        cities.add("San Pedro");
        cities.add("Alajuelita");
        cities.add("Tibás");
        cities.add("Escazú");
        cities.add("Moravia");
        cities.add("Ciudad Colón");
        cities.add("Guadalupe");
       //hola
        
        
        Collections.sort(cities);
        Lugares.addItem("Seleccione un lugar");
        cities.forEach(city -> {
            Lugares.addItem((String) city);
        });
     
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") ///
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        popupMenu3 = new java.awt.PopupMenu();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        Lugares = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        popupMenu3.setLabel("popupMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Atrás");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label1.setText("Más información sobre los lugares");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione un lugar ");

        Lugares.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LugaresItemStateChanged(evt);
            }
        });
        Lugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugaresActionPerformed(evt);
            }
        });

        mostrar.setColumns(20);
        mostrar.setRows(5);
        jScrollPane1.setViewportView(mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lugares, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141))))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        mainWindow main = new mainWindow();
        main.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void LugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugaresActionPerformed
   
    }//GEN-LAST:event_LugaresActionPerformed

    private void LugaresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LugaresItemStateChanged
        // TODO add your handling code here:
        String lugar = (String)Lugares.getSelectedItem();
        
        if (lugar.equals("Alajuelita"))
          mostrar.setText("Habitantes:\n" +"-12,875 \nLugares interés:\n" + "-Cruz de Alajuelita\n" + "-La Piedra del Minero \nComidas:\n" + "-Restaurante Mirador America\n" +
          "-La cabaña de Toño \nGasolineras:\n" + "-ANATOTC S.A\n" + "-Servicentro J.S.M Alajuelita" );

        if (lugar.equals("San Pedro"))
            mostrar.setText("Habitantes:\n" +"-23,977 \nLugares interés:\n" + "-UCR\n" + "-Outlet Mall  \nComidas:\n" + "-Chill&Go´s\n" + "-La Pataconería \nGasolineras:\n" +
            "-Servicentro el Higuerón\n" + "-Bomba San Pedro" );

        if (lugar.equals("Barbacoas"))
            mostrar.setText("Habitantes:\n" +"-3692 \nLugares interés:\n" + "-Mirador al Golfo de Nicoya\n" + "-Finca la Alejandría \nComidas:\n" + "-Bar Karibu\n" + 
            "-Donde Perola Puriscal \nGasolineras:\n" + "-No posee" );

        if (lugar.equals("Tibás"))
            mostrar.setText("Habitantes:\n" +"-82,216 \nLugares interés:\n" + "-Plaza Deportes Jardines \n" + "-Hospital UNIBE \nComidas:\n" + "-Monster Pizza\n" +
            "-KFC \nGasolineras:\n" + "-Delta Los Colegios \n" + "-Delta Tibás" );

        if (lugar.equals("Sabanilla"))
            mostrar.setText("Habitantes:\n" +"-10,775 \nLugares interés:\n" + "-Parque de Sabanilla\n" + "-Mall San Pedro \nComidas:\n" + "-Pizza Varel\n" + 
            "-McDonald´s Sabanilla \nGasolineras:\n" + "-No posee" );
        
        if (lugar.equals("Desamparados"))
            mostrar.setText("Habitantes:\n" +"-33,866 \nLugares interés:\n" + "-Multicentro Desamparados Mall\n" + "-Estadio Cuty Monge \nComidas:\n" + "-Sosa San Lorenzo\n" + 
            "-Soda Yoguis \nGasolineras:\n" + "-Metrópoli Gas LP\n" + "-Blueflame" );
        
        if (lugar.equals("Curridabat"))
            mostrar.setText("Habitantes:\n" +"-28,817 \nLugares interés:\n" + "-Cinemark\n" + "-Parque Guayabos \nComidas:\n" + "-Ramen Saki\n" +
            "-Los Parales \nGasolineras:\n" + "-La Galera\n" + "-Gasolinera y Gas LP El Ranchito" );
        
        if (lugar.equals("Aserrí"))
            mostrar.setText("Habitantes:\n" +"-28,191 \nLugares interés:\n" + "-Parque Acuático Los Sueños\n" + "-Parque de Aserrí \nComidas:\n" + "-Chicharronera Cacique Acserí\n" +
            "-Papa John's Pizza \nGasolineras:\n" + "-Gasolinera Trova\n" + "-Gasotica Aserrí" );
        
        if (lugar.equals("Santiago"))
            mostrar.setText("Habitantes:\n" +"-11,512 \nLugares interés:\n" + "-Parque del Agricultor" + "-Kamakiri Centro Recreativo \nComidas:\n" + "-Pops\n" +
            "-Heladería y Soda Caprichos \nGasolineras:\n" + "-Delta Puriscal\n" + "-Estación de Servicio San Juan" );
        
        if (lugar.equals("Hatillo"))
            mostrar.setText("Habitantes:\n" +"-50,511 \nLugares interés:\n" + "-Centro Comercial Plaza América " + "-Alpízar's Sport Center \nComidas:\n" + "-Pizza Hut\n" + 
            "-Burger King \nGasolineras:\n" + "-Lavacar las Américas\n" + "-UNO" );
        
        if (lugar.equals("Santa Ana"))
            mostrar.setText("Habitantes:\n" +"-60,453 \nLugares interés:\n" + "-Hacienda La Chimba\n " + "-Santa Ana Town Center \nComidas:\n" + "-McDonald’s\n" +
            "-Andiamo Là \nGasolineras:\n" + "-Gasolinera Montes\n" + "-Gasolinera Lindora y Gas Lp" );
        
        if (lugar.equals("Guadalupe"))
            mostrar.setText("Habitantes:\n" +"-20,663 \nLugares interés:\n" + "-Estadio José Joaquín “Colleya” Fonseca\n " + "-Parque Santiago Jara \nComidas:\n" + 
            "-Restaurante Copa de Oro\n" + "-Koralitos Marisquería  \nGasolineras:\n" + "-Gasolinera uno\n" + "-Montilermar Gasolinera" );
        
        if (lugar.equals("Ciudad Colón"))
            mostrar.setText("Habitantes:\n" +"-16,088 \nLugares interés:\n" + "-Los pochotes\n " + "-Waterfall Ciudad Colón \nComidas:\n" + "-Restaurante conservatorium\n" +
            "-Antojitos de Villa  \nGasolineras:\n" + "-Delta Mora\n" + "-Servicentro los Ángeles" );
        
        if (lugar.equals("Moravia"))
            mostrar.setText("Habitantes:\n" +"-61,148 \nLugares interés:\n" + "-Lincoln Plaza\n " + "-Parque de San Jerónimo \nComidas:\n" + "-Antojos de montaña\n" +
            "-Sabor de Maco  \nGasolineras:\n" + "-Llantera Surtimax\n" + "-Estación de servicio, servicentro Moravia" );
        
        if (lugar.equals("Escazú"))
            mostrar.setText("Habitantes:\n" +"56,509 \nLugares interés:\n" + "-Mirador Escondido\n " + "-Parque de Bello Horizonte \nComidas:\n" + "-La Casona De Laly\n" +
            "-La Posada de las Brujas  \nGasolineras:\n" + "No posee" );
        
        if (lugar.equals("Seleccione un lugar"))
            mostrar.setText("");
        
        
        
    }//GEN-LAST:event_LugaresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AyudaViajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Lugares;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JTextArea mostrar;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    // End of variables declaration//GEN-END:variables
}
